Repository donaldfilimon/abi, pull requests merged in 2025-09, with the labels that each got.

#53 Zig full codebase refactor
  .github/workflows/ci-refactored.yml
  .github/workflows/ci.yml
  CLEANUP_REPORT.md
  FEATURE_MIGRATION_MAP.md
  REFACTORING_PLAN.md
  REFACTORING_SUMMARY.md
  benchmarks/refactored_performance_test.zig
  build.zig
  build_refactored.zig
  deploy/docker/Dockerfile
  deploy/docker/docker-compose.yml
  deploy/kubernetes/wdbx-deployment.yaml
  deploy/scripts/deploy-production.sh
  deploy/scripts/deploy-staging.sh
  docs/ARCHITECTURE.md
  docs/MIGRATION_GUIDE.md
  examples/gpu_examples.zig
  examples/neural.zig
  examples/weather.zig
  examples/weather_ui.html
  src/api/cli/mod.zig
  src/api/mod.zig
  src/dynamic.zig
  src/localml.zig
  src/main.zig
  src/main_refactored.zig
  src/utils/errors.zig
  src/utils/mod.zig
  src/wdbx.zig
  src/wdbx_cli.zig
  src/wdbx_enhanced.zig
  src/wdbx_production.zig
  tests/test_core_integration.zig
  tests/test_lsh_index.zig
  tests/test_multilevel_cache.zig
  tests/test_vector_compression.zig
Labels: bug, documentation, enhancement, aby, codex

#52 Add advanced persona system sample
  README.md
  docs/advanced_persona_system.md
  scripts/test_advanced_persona.sh
  src/advanced_persona_system.zig
  src/advanced_persona_system_test.zig
Labels: bug, documentation, enhancement, help wanted, good first issue, aby, codex

#51 Update .gitignore with common build artifacts
  .gitignore
Labels: bug, documentation, enhancement, help wanted, aby, codex

#67 Fix Windows network test report header spacing
  src/tools/windows_network_test.zig
Labels: codex

#66 benchmarks: fix logging format for zig 0.16
  benchmarks/benchmark_framework.zig
  benchmarks/main.zig
Labels: codex

#72 docs: sort search index inputs
  src/tools/docs_generator.zig
Labels: codex

#73 docs: align zig 0.16 metadata with latest snapshot
  .zigversion
  CROSS_PLATFORM_TESTING_GUIDE.md
  MIGRATION_REPORT.md
  build.zig
  build.zig.zon
  deploy/docker/Dockerfile.gpu
  scripts/enhance_cross_platform_testing.sh
Labels: codex

#77 build: share abi module across executable and tests
  MIGRATION_REPORT.md
  build.zig
Labels: codex

#75 docs: sort search index inputs
  docs/generated/search_index.json
  src/tools/docs_generator.zig
Labels: codex

#80 framework: orchestrate runtime lifecycle
  docs/README.md
  docs/_config.yml
  docs/_layouts/documentation.html
  docs/assets/js/documentation.js
  docs/assets/js/search.js
  src/framework/catalog.zig
  src/framework/feature_manager.zig
  src/framework/mod.zig
  src/framework/runtime.zig
  src/framework/state.zig
  src/main.zig
  src/mod.zig
  src/root.zig
  src/shared/core/lifecycle.zig
  src/shared/loader.zig
  src/shared/registry.zig
Labels: codex

#82 framework: introduce runtime orchestrator
  README.md
  src/features/mod.zig
  src/framework/config.zig
  src/framework/mod.zig
  src/framework/runtime.zig
  src/main.zig
  src/mod.zig
Labels: codex

#78 Fix GitHub Pages documentation assets
  docs/README.md
  docs/_layouts/documentation.html
  docs/assets/js/documentation.js
  docs/assets/js/search.js
  src/tools/docs_generator.zig
Labels: codex

#79 docs: fix github pages navigation and assets
  docs/README.md
  docs/assets/js/documentation.js
  docs/assets/js/search.js
Labels: codex

#94 docs: expand zig 0.16 migration playbook
  MIGRATION_REPORT.md
Labels: codex

#84 wdbx: wire up http server and update cli docs
  README.md
  docs/api/wdbx.md
  src/features/database/cli.zig
  src/features/web/wdbx_http.zig
Labels: bug, enhancement, aby, codex

#92 database: use @Vector reductions
  src/features/database/database.zig
Labels: bug, enhancement, aby, codex

#90 Align Zig version documentation with .zigversion
  CONTRIBUTING.md
  DEPLOYMENT_GUIDE.md
  README.md
Labels: bug, enhancement, aby, codex

#89 docs: sync README CLI and testing guidance
  README.md
Labels: bug, enhancement, aby, codex

#96 build: run unit tests via run artifact
  build.zig
Labels: codex

#97 docs: document Db.freeResults cleanup
  README.md
Labels: codex

#100 Update WDBX CLI commands in README
  README.md
Labels: codex

#95 Update docs to reflect feature module layout
  README.md
  docs/MODULE_ORGANIZATION.md
  docs/TESTING_STRATEGY.md
Labels: codex

#85 build: pin zig 0.16.0-dev.254+6dd0270a1
  .github/workflows/deploy_docs.yml
  CHANGELOG.md
  CONTRIBUTING.md
  DEPLOYMENT_GUIDE.md
  README.md
  deploy/scripts/deploy-staging.ps1
  src/tools/docs_generator.zig
Labels: bug, enhancement, aby, codex

#110 Add deterministic GPU acceleration tests and CI lanes
  .github/workflows/ci.yml
  src/features/gpu/compute/gpu_ai_acceleration.zig
Labels: codex

#103 Update WDBX example cleanup guidance
  README.md
Labels: codex

#104 docs: fix agent response deallocation example
  README.md
Labels: codex

#105 docs: clarify wdbx cli invocation
  README.md
Labels: codex

#106 docs: expand zig 0.16 migration playbook
  MIGRATION_REPORT.md
Labels: codex

#109 docs: sync documentation with feature modules
  README.md
  docs/MODULE_ORGANIZATION.md
  docs/api/ai.md
  docs/api/database.md
  docs/api/index.md
  docs/api/plugins.md
  docs/api_reference.md
  docs/generated/API_REFERENCE.md
  docs/generated/EXAMPLES.md
  docs/generated/MODULE_REFERENCE.md
Labels: codex

#108 Run unit tests via zig build test
  build.zig
Labels: codex

#116 docs: add windows zig std troubleshooting guide
  docs/WINDOWS_ZIG_STD_DOCS_FIX.md
Labels: codex

#117 docs: summarize zig std windows regression
  docs/zig_std_windows_bug.md
Labels: codex

#111 gpu: enable native compute dispatch
  build.zig
  docs/GPU_AI_ACCELERATION.md
  src/features/gpu/compute/gpu_ai_acceleration.zig
  src/features/gpu/core/gpu_renderer.zig
Labels: codex

#113 docs: add zig std windows workaround guide
  docs/README.md
  docs/ZIG_STD_WINDOWS_FIX.md
Labels: codex

#121 docs: refresh windows zig std guide
  docs/WINDOWS_ZIG_STD_DOCS_FIX.md
Labels: codex

#118 docs: refresh windows zig std troubleshooting guide
  docs/WINDOWS_ZIG_STD_DOCS_FIX.md
Labels: codex

#123 docs: fix windows troubleshooting link
  docs/README.md
Labels: codex

#136 docs: rewrite changelog and surface release notes
  CHANGELOG.md
  scripts/release.sh
Labels: codex

#134 abi: re-export feature modules
  src/mod.zig
Labels: codex

#129 framework: sync loader paths on clear
  src/framework/runtime.zig
Labels: codex

#143 build: export package version to abi module
  build.zig
  src/mod.zig
Labels: codex

#149 Merge codex branches into work branch
  CHANGELOG.md
  CONTRIBUTING.md
  README.md
  build.zig
  build.zig.zon
  docs/GPU_AI_ACCELERATION.md
  docs/MODULE_ORGANIZATION.md
  docs/PRODUCTION_DEPLOYMENT.md
  docs/README.md
  docs/TESTING_STRATEGY.md
  docs/WINDOWS_ZIG_STD_DOCS_FIX.md
  docs/ZIG_STD_WINDOWS_FIX.md
  docs/_config.yml
  docs/api/index.md
  docs/api_reference.md
  docs/generated/CODE_API_INDEX.md
  docs/zig_std_windows_bug.md
  scripts/release.ps1
  scripts/release.sh
  src/features/database/cli.zig
  src/features/database/core.zig
  src/features/database/unified.zig
  src/framework/runtime.zig
  src/mod.zig
  src/shared/mod.zig
  src/shared/utils/utils.zig
  src/tools/main.zig
  tools/zig_docs_interactive.ps1
Labels: codex

#154 Add documentation build pipeline
  build.zig
  docs/README.md
  src/tools/docs_generator.zig
Labels: codex

#168 Fix stdout writer usage for Zig 0.16
  src/main.zig
Labels: codex

#164 Consolidate Markdown Status Reports
  BENCHMARK_UPGRADE_SUMMARY.md
  CODEBASE_IMPROVEMENTS_SUMMARY.md
  CROSS_PLATFORM_ENHANCEMENT_SUMMARY.md
  CROSS_PLATFORM_TESTING_GUIDE.md
  DEPLOYMENT_GUIDE.md
  DEPLOYMENT_READY.md
  MIGRATION_REPORT.md
  README.md
  UTILITIES_IMPLEMENTATION_SUMMARY.md
  docs/reports/cross_platform_testing.md
  docs/reports/engineering_status.md
  scripts/enhance_cross_platform_testing.sh
Labels: documentation, enhancement, aby, codex

#138 Prepare 0.1.0a prerelease metadata
  CHANGELOG.md
  README.md
  src/features/database/core.zig
  src/features/database/unified.zig
  src/mod.zig
  src/tools/main.zig
Labels: bug, documentation, enhancement, help wanted, good first issue, question, aby, codex

#183 Refactor GPU renderer into modular backend architecture
  build.zig
  src/features/ai/activations/functions.zig
  src/features/ai/activations/mod.zig
  src/features/ai/activations/utils.zig
  src/features/ai/ai_core.zig
  src/features/ai/distributed/mod.zig
  src/features/ai/distributed/training.zig
  src/features/ai/interfaces.zig
  src/features/ai/layer.zig
  src/features/ai/mod.zig
  src/features/ai/optimizers/config.zig
  src/features/ai/optimizers/mod.zig
  src/features/ai/serialization/mod.zig
  src/features/ai/serialization/serializer.zig
  src/features/gpu/compute/gpu_ai_acceleration.zig
  src/features/gpu/core/gpu_renderer.zig
  src/features/gpu/core/gpu_renderer/backends.zig
  src/features/gpu/core/gpu_renderer/backends/cpu.zig
  src/features/gpu/core/gpu_renderer/backends/cuda.zig
  src/features/gpu/core/gpu_renderer/backends/dx12.zig
  src/features/gpu/core/gpu_renderer/backends/metal.zig
  src/features/gpu/core/gpu_renderer/backends/opencl.zig
  src/features/gpu/core/gpu_renderer/backends/opengl.zig
  src/features/gpu/core/gpu_renderer/backends/vulkan.zig
  src/features/gpu/core/gpu_renderer/backends/webgpu.zig
  src/features/gpu/core/gpu_renderer/buffers.zig
  src/features/gpu/core/gpu_renderer/config.zig
  src/features/gpu/core/gpu_renderer/mod.zig
  src/features/gpu/core/gpu_renderer/pipelines.zig
  src/features/gpu/core/gpu_renderer/renderer.zig
  src/features/gpu/core/gpu_renderer/types.zig
  src/tools/docs_generator/config.zig
  src/tools/docs_generator/generators/api_reference.zig
  src/tools/docs_generator/generators/code_index.zig
  src/tools/docs_generator/generators/definitions_reference.zig
  src/tools/docs_generator/generators/docs_index.zig
  src/tools/docs_generator/generators/examples.zig
  src/tools/docs_generator/generators/module_docs.zig
  src/tools/docs_generator/generators/native_docs.zig
  src/tools/docs_generator/generators/performance_guide.zig
  src/tools/docs_generator/generators/readme_redirect.zig
  src/tools/docs_generator/generators/search_index.zig
  src/tools/docs_generator/tests.zig
Labels: codex

#188 Align module exports with Zig 0.16
  docs/CODE_API_INDEX.md
  src/features/ai/activations/mod.zig
  src/features/ai/ai_core.zig
  src/features/ai/distributed/mod.zig
  src/features/ai/optimizers/mod.zig
  src/features/ai/serialization/mod.zig
  src/features/gpu/core/gpu_renderer.zig
  src/features/gpu/core/gpu_renderer/buffers.zig
  src/features/gpu/core/gpu_renderer/mod.zig
  src/features/gpu/core/gpu_renderer/renderer.zig
Labels: codex

#189 Add persona manifest loader and observability primitives
  config/personas/default.json
  docs/CODE_API_INDEX.md
  src/features/ai/agent.zig
  src/features/gpu/core/gpu_renderer/buffers.zig
  src/shared/core/config.zig
  src/shared/core/mod.zig
  src/shared/core/persona_manifest.zig
  src/shared/core/profiles.zig
  src/shared/mod.zig
  src/shared/observability/metrics.zig
  src/shared/observability/mod.zig
  src/shared/observability/trace.zig
Labels: codex

#190 Add persona manifest loader and CLI manifest support
  deploy/personas/README.md
  deploy/personas/dev.toml
  docs/CODE_API_INDEX.md
  src/features/ai/mod.zig
  src/features/ai/persona_manifest.zig
  src/tools/cli/chat.zig
Labels: codex

#193 Refactor CLI registry into typed modules
  src/tools/cli/chat.zig
  src/tools/cli/common.zig
  src/tools/cli/config.zig
  src/tools/cli/db.zig
  src/tools/cli/gpu.zig
  src/tools/cli/llm.zig
  src/tools/cli/neural.zig
  src/tools/cli/plugin.zig
  src/tools/cli/registry.zig
  src/tools/cli/router.zig
  src/tools/cli/server.zig
  src/tools/cli/simd.zig
  src/tools/cli/weather.zig
  tests/tools_cli.zig
Labels: codex

#195 Modularize GPU renderer entrypoint and add module tests
  src/features/gpu/core/gpu_renderer/backends/cpu.zig
  src/features/gpu/core/gpu_renderer/buffers.zig
  src/features/gpu/core/gpu_renderer/config.zig
  src/features/gpu/core/gpu_renderer/pipelines.zig
  src/features/gpu/gpu_renderer.zig
  src/features/gpu/mod.zig
Labels: codex

#198 feat: rebuild comprehensive CLI for structured output
  src/comprehensive_cli.zig
Labels: codex

#201 Remove obsolete CLI summary artifacts
  CLI_GPU_COMPLETION_SUMMARY.md
  CLI_SERVICES_IMPLEMENTATION_SUMMARY.md
  FULL_FUNCTIONALITY_IMPLEMENTATION_SUMMARY.md
  MODERNIZATION_STATUS.md
  build.zig
  build.zig.zon
Labels: codex

#206 Fix SessionDatabase metadata ownership and add regression test
  src/comprehensive_cli.zig
Labels: codex

#207 Fix SessionDatabase metadata ownership bugs
  src/comprehensive_cli.zig
Labels: codex

#210 Correct metadata errdefer scope in SessionDatabase insert
  src/comprehensive_cli.zig
Labels: bug, aby, codex
